import ilog.concert.IloException;

import java.util.*;

/**
 * 分支定价（Branch-and-Price）精确求解装箱问题。
 *
 * 框架：
 *   1. FFD 贪心给出初始上界（incumbent）；
 *   2. 显式维护搜索树节点栈（DFS），每个 {@link Node} 携带自己的有效物品、
 *      冲突约束与继承列池；
 *   3. 循环：弹出节点 -> 列生成求 LP 下界 ->
 *        不可行 / 被上界剪枝  -> 丢弃；
 *        LP 解已整            -> 更新上界；
 *        否则按 Ryan-Foster 在物品对 (a,b) 上分支；
 *   4. two children generated by {@code new Node(inst, node, a, b, anb)} 压栈；
 *   5. 栈空 -> 搜索树穷尽，当前上界即最优解。
 *
 * 分支规则（Ryan-Foster）：不能直接对分数变量 y_s 分支（会破坏定价子问题的背包结构），
 * 改为对物品对分支：together = 合并成有效物品；separate = 定价问题加冲突约束。
 * 定理保证分支树有限且不遗漏最优解。
 */
public class BranchAndPrice {

    private static final double EPS = 1e-6;
    /** 是否打印每个节点的 LP 解向量（调试用）。 */
    private static final boolean VERBOSE = false;

    private final double capacity;
    private double incumbent = Double.MAX_VALUE;   // 当前最优箱子数（上界）
    private List<Set<Integer>> bestBins;           // 当前最优装箱方案
    private double rootLpBound = -1;

    private int processedNodes = 0;                // 已求解的节点数
    private int generatedNodes = 0;                // 已生成的节点总数（含根）
 //   private final Map<Node.Status, Integer> stats = new EnumMap<>(Node.Status.class);

    public BranchAndPrice(Instance inst) {
        this.capacity = inst.capacity;
    }

    /** 求解结果。 */
    public static class Result {
        public final int bins;                     // 最优箱子数
        public final List<Set<Integer>> solution;  // 每个箱子包含的原始物品编号
        public final int nodes;                    // 搜索节点数（已处理）
        public final double rootLpBound;           // 根节点 LP 下界
        public final int ffdBound;                 // FFD 贪心上界
        public final int generatedNodes;           // 生成的节点总数
        public final boolean provenOptimal;        // 搜索树是否穷尽

        Result(int bins, List<Set<Integer>> solution, int nodes,
               double rootLpBound, int ffdBound) {
            this(bins, solution, nodes, rootLpBound, ffdBound, nodes, true);
        }

        Result(int bins, List<Set<Integer>> solution, int nodes,
               double rootLpBound, int ffdBound, int generatedNodes, boolean provenOptimal) {
            this.bins = bins;
            this.solution = solution;
            this.nodes = nodes;
            this.rootLpBound = rootLpBound;
            this.ffdBound = ffdBound;
            this.generatedNodes = generatedNodes;
            this.provenOptimal = provenOptimal;
        }
    }

    // ==================================================================
    //                          主循环
    // ==================================================================

    public Result solve(Instance inst) throws IloException {
        // ---- 初始上界：FFD 贪心 ----
        List<Set<Integer>> ffd = firstFitDecreasing(inst);
        incumbent = ffd.size();
        bestBins = ffd;
        System.out.println("FFD 贪心上界: " + incumbent);

        // ---- 根节点 ----
        Node.cnt = 0;
        Node root = new Node(inst);
        generatedNodes = 1;

        // ---- 显式搜索树：DFS（后进先出） ----
        Deque<Node> open = new ArrayDeque<>();
        open.push(root);

        while (!open.isEmpty()) {
            Node node = open.pop();
            processedNodes++;

            // ========== 阶段 1：列生成，求节点 LP 下界 ==========
            solveNodeLp(node);
            if (node.status == Node.Status.INFEASIBLE) {     // RMP 不可行 -> 剪枝
                // tally(Node.Status.INFEASIBLE);
                continue;
            }
            if (node.isRootNode()) rootLpBound = node.lb;
            logNode(node);

            // ========== 阶段 2：剪枝（LP 下界取整后不小于当前上界） ==========
            if (Math.ceil(node.lb - 1e-4) >= incumbent - EPS) {
                node.status = Node.Status.PRUNED;
               // tally(Node.Status.PRUNED);
                continue;
            }

            // ========== 阶段 3：整数性判定 / Ryan-Foster 选分支对 ==========
            int[] pair = chooseBranchPair(node.y, node.columns);
            if (pair == null) {                              // LP 解已是整数解
                updateIncumbent(node);
                node.status = Node.Status.INTEGER;
              //  tally(Node.Status.INTEGER);
                continue;
            }

            // ========== 阶段 4：分支 ==========
            node.branchPair = pair;
            node.status = Node.Status.BRANCHED;
          //  tally(Node.Status.BRANCHED);

            Node sep = new Node(inst, node, pair[0], pair[1], false);
            Node tog = new Node(inst, node, pair[0], pair[1], true);

            // DFS 先探 together 分支：栈后进先出，故 separate 先入栈
            open.push(sep);
            if (tog.isFeasible()) open.push(tog);
        }

        generatedNodes = Node.cnt;          // 含因超容量/矛盾而未入栈的 together 子节点
     //   printSummary();
        return new Result((int) incumbent, bestBins, processedNodes,
                rootLpBound, ffd.size(), generatedNodes, true);
    }

    /**
     * 在给定节点上运行列生成（RMP <-> Pricing 交替），结果写回节点。
     *
     * 先用节点继承的列池 warm start：子节点生成时已做过相容性过滤与下标重映射，
     * 池中列都是本节点的合法模式；再补单物品列以保证 RMP 始终可行。
     */
    private void solveNodeLp(Node node) throws IloException {
        // 表示一个节点中的有效物品集合，及其对应的 LP 列池（模式）和 LP 取值
        ArrayList<EffItem> items = node.items;
        try (MasterProblem master = new MasterProblem(items.size())) {
            Set<String> seen = new HashSet<>();

            // 1) warm start：继承父节点的列
            //TODO: 对于这里的模型的创建过程，是不是可以在节点处就创建好模型，然后在这里再添加列，而不是每次都重新创建模型？
            for (int[] col : node.columns) {
                if (seen.add(Node.columnKey(col))){
                    master.addColumn(col);
                }
            }
            // 2) 单物品列：保证 RMP 可行且覆盖所有物品
            for (int e = 0; e < items.size(); e++) {
                int[] single = new int[]{e};
                if (seen.add(Node.columnKey(single))) master.addColumn(single);
            }

            // 3) 列生成：不断追加 reduced cost < 0 的列，直到没有改进列
            while (true) {
                double[] pi = master.solve();
                node.n_lp++;
                if (pi == null) {                            // RMP 不可行
                    node.status = Node.Status.INFEASIBLE;
                    return;
                }
                int[] pattern = PricingProblem.solve(items, node.cfc, pi, capacity);
                if (pattern == null) break;                  // 无负 reduced cost -> 收敛
                if (!seen.add(Node.columnKey(pattern))) break; // 重复列（兜底防死循环）
                master.addColumn(pattern);
            }

            node.lb = master.objectiveValue();
            node.y = master.columnValues();
            node.columns = new ArrayList<>(master.getColumns()); // 回写列池供子节点复用
            node.status = Node.Status.SOLVED;

            //当前节点的 LP 解向量和列数打印出来，便于调试和分析
            if (VERBOSE) {
                System.out.println("  LP solution: " + Arrays.toString(node.y));
                System.out.println("  columns    : " + node.columns.size());
            }
        }
    }

    /**
     * Ryan-Foster 分支对选择：
     * 对每个分数列 s（0 < y_s < 1）中出现的物品对 (i,j)，累加 f_ij = sum_{s>= {i,j}} y_s。
     * 若存在 0 < f_ij < 1 则选其分支；若所有 f_ij 均为 0/1，则 LP 解必为整数解
     * （Ryan-Foster 定理）。选取 f_ij 最接近 0.5 的对以平衡分支树。
     */
    private int[] chooseBranchPair(double[] y, List<int[]> cols) {
        Map<Long, Double> f = new HashMap<>();
        for (int s = 0; s < cols.size(); s++) {
            if (y[s] <= EPS || y[s] >= 1.0 - EPS) continue;  // 只看分数列
            int[] col = cols.get(s);                          // 模式 s 包含的有效物品下标
            //对于模式 s 中的每一对物品 (a,b)，累加 f_ij
            for (int a = 0; a < col.length; a++) {
                for (int b = a + 1; b < col.length; b++) {
                    f.merge(pairKey(col[a], col[b]), y[s], Double::sum);
                }
            }
        }
        int[] best = null;
        double bestScore = -1.0;
        //选择所有的 f_ij 中最接近 0.5 的对 (i,j) 作为分支对
        for (Map.Entry<Long, Double> e : f.entrySet()) {
            double v = e.getValue();
            if (v > EPS && v < 1.0 - EPS) {
                double score = Math.min(v, 1.0 - v);         // 越接近 0.5 分数越高
                //更新最优分支对
                if (score > bestScore) {
                    bestScore = score;
                    best = unkey(e.getKey());
                }
            }
        }
        return best;
    }

    /** LP 解整时把它转成可行装箱方案并尝试更新上界。 */
    private void updateIncumbent(Node node) {
        List<Set<Integer>> bins = new ArrayList<>();
        // 每个取值 >= 1 的列对应一个箱子，列中有效物品展开成原始物品
        for (int s = 0; s < node.columns.size(); s++) {
            if (node.y[s] < 1.0 - EPS) continue;
            Set<Integer> bin = new TreeSet<>();
            for (int e : node.columns.get(s)) bin.addAll(node.items.get(e).origItems);
            bins.add(bin);
        }
        // 去重：同一物品出现在多个箱子时归入第一个箱子，再删掉空箱
        Set<Integer> seen = new HashSet<>();
        List<Set<Integer>> cleaned = new ArrayList<>();
        for (Set<Integer> bin : bins) {
            Set<Integer> nb = new TreeSet<>();
            for (int it : bin) {
                if (seen.add(it)) nb.add(it);
            }
            if (!nb.isEmpty()) cleaned.add(nb);
        }
        if (cleaned.size() < incumbent) {
            incumbent = cleaned.size();
            bestBins = cleaned;
            System.out.println("New incumbent: " + incumbent
                    + " bins, node #" + node.no + " (depth=" + node.depth + ")");
        }
    }

    // ==================================================================
    //                          日志 / 工具
    // ==================================================================

    private void logNode(Node node) {
        System.out.printf("节点 #%-3d depth=%-2d LP=%-9.4f ceil(LP)=%-3d 上界=%.0f  列数=%-4d %s%n",
                node.no, node.depth, node.lb,
                (int) Math.ceil(node.lb - 1e-4), incumbent,
                node.columns.size(), node.getBranchPath());
    }
/*
    private void tally(Node.Status s) {
        stats.merge(s, 1, Integer::sum);
    }
*/
//    private void printSummary() {
//        System.out.println("---- 搜索树统计 ----");
//        System.out.println("生成节点总数 : " + generatedNodes);
//        System.out.println("已处理节点数 : " + processedNodes);
//        System.out.println("  不可行剪枝 : " + stats.getOrDefault(Node.Status.INFEASIBLE, 0));
//        System.out.println("  上界剪枝   : " + stats.getOrDefault(Node.Status.PRUNED, 0));
//        System.out.println("  整数解     : " + stats.getOrDefault(Node.Status.INTEGER, 0));
//        System.out.println("  分支节点   : " + stats.getOrDefault(Node.Status.BRANCHED, 0));
//        System.out.println("搜索树已穷尽 -> 最优性已证明");
//    }

    /**
     * 将两个整数 a、b 组合成一个唯一的长整型键值（与顺序无关）：
     * 较小数 * 1,000,000 + 较大数。
     */
    private static long pairKey(int a, int b) {
        return (long) Math.min(a, b) * 1_000_000L + Math.max(a, b);
    }

    /** pairKey 的逆运算，解码回原始整数对。 */
    private static int[] unkey(long key) {
        return new int[]{(int) (key / 1_000_000L), (int) (key % 1_000_000L)};
    }

    /** First-Fit-Decreasing 贪心：给出初始可行上界。 */
    public static List<Set<Integer>> firstFitDecreasing(Instance inst) {
        Integer[] order = new Integer[inst.n()];
        for (int i = 0; i < order.length; i++) order[i] = i;
        // 按重量降序排列物品，排的是索引，便于后续装箱时直接使用原始物品编号
        Arrays.sort(order, (a, b) -> Double.compare(inst.weights[b], inst.weights[a]));

        List<Set<Integer>> bins = new ArrayList<>();
        List<Double> residual = new ArrayList<>();
        // 从大到小依次尝试放入已有箱子，若都放不下则新开一个箱子
        for (int idx : order) {
            double w = inst.weights[idx];
            boolean placed = false;
            for (int b = 0; b < bins.size(); b++) {
                if (residual.get(b) + EPS >= w) {            // 能放下就放进去
                    bins.get(b).add(idx);
                    residual.set(b, residual.get(b) - w);
                    placed = true;
                    break;
                }
            }
            if (!placed) {
                Set<Integer> nb = new TreeSet<>();
                nb.add(idx);
                bins.add(nb);
                residual.add(inst.capacity - w);
            }
        }
        // 返回装箱方案：每个箱子包含的原始物品编号
        return bins;
    }
}
